### ISSUE TITLE
Search for books

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#1]
## Value proposition
As a user, I want to search for books based on name, author or ISBN in order to find exactly the book that I want.

## Description
![CleanShot 2021-06-03 at 15 59 25](https://user-images.githubusercontent.com/82387427/120657456-cc76d880-c484-11eb-91de-3730e07c617a.png)

## Acceptance criteria

- [x] Entering search term (book title, author, ISBN) returns search results
- [x] Search results are displayed as boxes with image, title and author shown to make selection process easy for user
- [x] 'Add' Button is already included in the box

## Complexity
L

## Tasks

- [x] New feature branch 'search'
- [x] Add search bar component 
- [x] Set up backend
- [x] Implement controller, routers and server.js logic
- [x] Use backend to fetch Google Books API
- [x] Fetch Google Books API
- [x] Implement search logic
- [x] POST Search Query to backend and use response to display search results
- [x] Add tests
- [x] Add styleguidist component for search bar
