### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#12]
## Value Statement

As a user, I would like to see a consistent header on the page in order to know which great app I am using and always be able to get back to the home page.

## Description

![CleanShot 2021-06-14 at 16 02 39](https://user-images.githubusercontent.com/82387427/121904985-f607ed80-cd29-11eb-93ec-6211129b14e9.png)

## Acceptance Critera

- [x] Header appears on all pages
- [x] Header includes Logo
- [x] Click on Logo redirects to /home

## Complexity
S

## Tasks

- [x] Create feature branch 'feat-header'
- [x] Add header component
- [x] Import Icon
- [x] Implement Routing
- [x] Implement it on all pages
- [x] Add to styleguidist
