### ISSUE TITLE
Show book details

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#15]
## Value Statement
As a user I want to be able to see details for a book after clicking on it in order to get a better overview of the book.

## Description

![CleanShot 2021-06-16 at 18 26 17](https://user-images.githubusercontent.com/82387427/122257496-5c2e7500-ced0-11eb-9a54-71abd23e776d.png)

## Acceptance Criteria

- [x] Click on a book opens details for that book
- [x] Major details such as title, author, releasedate, ISBN# etc are shown
- [x] Rating, Lent Status and Compartment are shown

## Complexity
M

## Tasks

- [x] Create feature branch 'feat-bookDetails'
- [x] Set up bookdetails component
- [x] Implement functionality and render logic
- [x] Add tests
- [x] Add styleguidist for component
