### ISSUE TITLE
Save new bookshelf

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#17]
## Value Statement
As a user I want to be able to save my created bookshelf in order for me to view it later and store books in it.

## Description
![CleanShot 2021-06-18 at 09 39 17](https://user-images.githubusercontent.com/82387427/122525008-129d7180-d019-11eb-958f-ff3a3068eb7c.png)

## Acceptance Criteria

- [x] Clicking Save button saves shelf in shelves array

## Complexity
S

## Tasks

- [x] Create feature branch 'feat-saveShelf'
- [x] Implement save button
- [x] Implement save logic
- [x] Implement notifications
- [x] Add styleguidist
