### ISSUE TITLE
Create bookshelf

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#2]
## Value Statement
As a user, I want to be able to recreate my real bookshelf as an empty bookshelf in the app in order to be able to place books into it later on.

## Description

![CleanShot 2021-06-03 at 16 21 56](https://user-images.githubusercontent.com/82387427/120660675-d9e19200-c487-11eb-844e-9fec0126e848.png)

## Acceptance Criteria

- [x] Entering / selecting number of shelves draws number of shelves in box below
- [x] Selecting number of compartments for each shelf draws the compartments in each shelf
- [x] Selecting a color from the color picker will change the color of the shelves.

## Complexity
L

## Tasks

- [x] New feature branch 'shelf-creator'
- [x] Create component for shelf attributes selector
- [x] Create component for shelf preview area 
- [x] Implement drawing logic
- [x] Add tests
- [x] Add styleguidist components for both components
