### ISSUE TITLE
Show shelf compartment content

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#22]
## Value Statement
As a user I want to be able to click on a shelf compartment in order to be able to see the stored books inside it on one page.

## Description
![CleanShot 2021-06-23 at 12 05 40](https://user-images.githubusercontent.com/82387427/123078687-807fd980-d41b-11eb-87f3-20f41f2fc509.png)

## Acceptance Criteria
- [x] Clicking on a compartment opens a new page for that compartment
- [x] Compartment page shows name, books and a back button
- [x] back button returns back to shelf page

## Complexity
M

## Tasks

- [x] Create feature branch 'feat-compartmentPage'
- [x] Add compartment component
- [x] Add routing to shelves in order to render correct compartment
- [x] Add styleguidist
- [x] Potentially add tests
