### ISSUE TITLE
Display bookshelf with books

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#24]
## Value Statement 
As a user I want to be able to see (a portion) of the books I have stored in a compartment when viewing my shelf.

## Description
![CleanShot 2021-06-24 at 16 43 30](https://user-images.githubusercontent.com/82387427/123283086-5574b300-d50b-11eb-9f97-a1b2f922904d.png)

## Acceptance Criteria

- [x] Book Cover Images are rendered when rendering shelf
- [x] Correct covers are displayed in the correct compartment
- [x] If there are more than 4 books, the first four covers are shown and a bubble display the number of additional books

## Complexity
L

## Tasks

- [x] Create feature branch 'feat-renderBooksInShelf'
- [x] Get BookImageURLs based on storedBooks-Array
- [x] Style covers so that they do not overflow or overlap or are too large
- [x] Implement logic for book count bubble
- [x] Add Tests
- [x] Add to Styleguidist
