### ISSUE TITLE
Home Dashboard

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#26]
## Value Statement
As a user, I want to see my shelves and my recently added books on the home screen in order to get an overview of my catalogue.

## Description
![CleanShot 2021-06-26 at 12 38 41](https://user-images.githubusercontent.com/82387427/123510392-79ef9d00-d67b-11eb-8d74-7977c728293b.png)

## Acceptance Criteria

- [x] /home includes dashboard including search bar, collection of shelves and recently added books
- [x] Using the search bar still renders search results
- [x] Clicking on shelfs section leads you to /myshelves
- [x] Clicking on books section leads to library
- [x] Clicking on single book opens details for that book

## Complexity
M

## Tasks

- [x] Create feature branch 'feat-dashboard'
- [x] Create dashboard components
- [x] Include them on Home.js
- [x] Create function to determine number of books in shelf
- [x] Create date function
- [x] Create routing
- [x] Add styleguidist
