### ISSUE TITLE
Login and Registration

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#27]
## Value Statement
As a user I want to be able to log in or register on the app in order for the app to remember me and load my data.

## Description
no image.

## Acceptance Criteria

- [x] User can create new user or sign in as existing one
- [x] Creating a new user redirects user to /firstShelf page to create a new shelf.
- [x] Signing in redirects to /home
- [x] If user already exists, it's not possible to create a new one with the same name
- [x] If user does not exist, it's not possible to sign in as that user

## Complexity
M

## Tasks

- [x] Create feature branch feat-startLogin
- [x] Create Start Page with buttons to sign in or start
- [x] Create Access Page where the user enters their (desired) user name
- [x] Create logic for adding new users, checking if user exists, checking if user is new, selecting active user
- [x] Create "firstShelf" page for new users.
