### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#29]
## Value Statement
As a user I want to be able to log out in order to be able to sign in as a different user 

## Description
Logout button

## Acceptance Criteria

- [x] Clicking button redirects user to /
- [x] Clicking button logs user out

## Complexity
S

## Tasks

- [x] Create branch 'feat-logout'
- [x] Implement button
- [x] Implement routing and state logic
