### ISSUE TITLE
Persisting books and shelves

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#3]
## Value Statement
As a user I want to be able store my created shelves and added books in order for my library and shelves to persist when re-open or reload the app.

## Description
![CleanShot 2021-06-03 at 17 08 44](https://user-images.githubusercontent.com/82387427/120668034-5ecfaa00-c48e-11eb-86de-2694631389bd.png)
![CleanShot 2021-06-03 at 17 08 55](https://user-images.githubusercontent.com/82387427/120668071-6727e500-c48e-11eb-92e0-b030289d8b18.png)

## Acceptance criteria

- [x] Books are still exactly as they were before reloading / restarting the app.
- [x] Shelves are still exactly as they were before reloading / restarting the app.

## Complexity
L

## Tasks

- [x] Create backend api with Express and Mongoose
- [x] Create routes, controllers for GET, POST, PUT operations
- [x] Connect frontend to backend 
- [x] Store to and load from local storage
