### ISSUE TITLE
Search in book library

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#35]
## Value Description
As a user I want to be able to search in my library to find the book I am looking for

## Acceptance Criteria

- [x] Searching in library returns correct books based on commonly used search criteria such as author, title, release year

## Complexity
M

## Tasks

- [x] Create feature branch
- [x] Add search bar to /mybooks
- [x] Add search functionality
