### ISSUE TITLE
Mark books as read / unread

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#36]
## Value Statement
As a user I want to be able to mark books as read or unread.

## Acceptance Criteria

- [x] Button toggles if book is read or unread. 
- [x] Saves status to database
- [x] Saves date (if switched to read) to library (for later use)

## Complexity
M

## Tasks

- [x] Create feature branch
- [x] Implement toggle functionality
- [x] Save to database
