### ISSUE TITLE
Button to remove searchinput

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#37]
## Value Statement
As a user I want to be able to remove my search input easily and quickly to make sure the search  results disappear

## Acceptance Criteria

- [x] Pressing Escape deletes search bar input
- [x] Clicking the X icon deletes search bar input

## Complexity 
S

## Tasks

- [x] Create feature branch
- [x] Add functionality to search bar
- [x] Make sure it works on every instance where search is implemented
