### ISSUE TITLE
Add notes to books

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#38]
## Value Statement
As a user I want to be able to add notes to my books in order to memorise important information

## Acceptance Criteria

- [x] Added notes are saved to the database and retrieved every time the book details are opened.

## Complexity
M

## Tasks

- [x] Create feature branch
- [x] Add controlled inputs
- [x] Add save functionality
