### ISSUE TITLE
Mark books as lent

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#39]
## Value Statement
As a user I want to be able to mark my books as lent and if yes, add the person I lent the book to with a date.

## Acceptance Criteria

- [x] Lent status, person and date are stored in the database and retrieved every time.

## Complexity
M

## Tasks

- [x] Create feature branch
- [x] Add controlled inputs
- [x] Add save functionality
