### ISSUE TITLE
Add books to library

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#4]
## Value Statement
As a user I want to add a book from the search results (or after scanning) to my library in order to be able to add them to bookshelves later.

## Description
![CleanShot 2021-06-03 at 19 07 07](https://user-images.githubusercontent.com/82387427/120684403-ede4be00-c49e-11eb-9928-e9e82817ba63.png)

## Acceptance criteria

- [x] Click on "Add" button adds book to library
- [x] "Add" button changes to another state, such as "Remove"
- [x] Clicking "Remove" button removes book from library

## Complexity
M

## Tasks

- [x] New feature branch 'add-books'
- [x] Create Add Button component
- [x] Implement Adding/removing logic
- [x] Implement button toggle
- [x] Add tests
- [x] Add styleguidist component for add button
