### ISSUE TITLE
Filter book library

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#47]
## Value Statement
As a user I want to be able to filter my books for certain criteria such as unread status, favorites or lent status in order to get a quick overview over my library.

## Description
<img width="416" alt="CleanShot 2021-07-05 at 22 19 39@2x" src="https://user-images.githubusercontent.com/82387427/124515222-27cb1c00-dddf-11eb-8686-96ff921f58c9.png">

## Acceptance Criteria

- [x] Clicking on button filters for that criteria
- [x] Active button is highlighted as such
- [x] Clicking again toggles the filter off
- [x] Clicking another button or searching also toggles the filter off

## Complexity 
S

## Tasks

- [x] Create feature branch 'feat-filterLibrary'
- [x] Add buttons to /mybooks page
- [x] Add functions to buttons
- [x] Add styling to buttons
