### ISSUE TITLE
Scan books to add them to library

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#48]
## Value Statement
As a user I want to be able to scan my books' barcodes in order to find them easily and add them quicker

## Acceptance Criteria

- [x] Clicking on camera button opens scanner
- [x] Scanner locates barcode and detects code
- [x] Upon detection, scanner closes automatically and pastes the result in the search bar
- [x] Search is initiated automatically after detection

## Complexity
L

## Tasks

- [x] Create feature branch 'feat-barcodeScanner'
- [x] Find matching barcode scanner to implement
- [x] Implement barcode scanner and adjust it to fit app
