### ISSUE TITLE
Add book to bookshelf

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#5]
## Value Statement
As a user I want to be able to add a book that's part of my library to one of my bookshelves, in a specific compartment in order to be able to depict my real-life bookshelf.

## Description

![CleanShot 2021-06-03 at 19 20 35](https://user-images.githubusercontent.com/82387427/120686046-da3a5700-c4a0-11eb-83ad-0b0971616829.png)

## Acceptance Criteria

- [x] User can select bookshelf from a dropdown menu
- [x] User can select specific compartment from a second dropdown that is dynamically filled based on first
- [x] Saving the selection will add / move the book to that compartment but still keep it in the general library

## Complexity
L

## Tasks

- [x] New feature branch 'shelf-selector'
- [x] Create Shelf-Selector component
- [x] Implement logic to put book into correct array
- [x] Add styleguidist component for shelf-selector
