### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#6]
## Value Statement
As a user, I want to be able to navigate between the pages so that I can access different parts of the page easily.

## Description
![CleanShot 2021-06-09 at 11 26 35](https://user-images.githubusercontent.com/82387427/121329506-91a5f200-c915-11eb-9edf-8638fb14fbb3.png)

## Acceptance Criteria

- [x] Navigation is pinned to bottom of page
- [x] Clicking on a navigation item redirects to that page
- [x] Active page icon is highlighted

## Complexity

M

## Tasks

- [x] New feature branch 'navigation'
- [x] Set up components, pages and images folders
- [x] Add navbar component
- [x] Import icons
- [x] Implement react router logic
- [x] Add tests
- [x] Add styleguidist component for nav bar
