### ISSUE TITLE
Display book library

### ISSUE THREAD

**Issue by sacidcelik** [sacidcelik/capstone-project#9]
## Value Statement
As a user I want to be able to see all my books on one page in order to get an overview of my library.

## Description
![CleanShot 2021-06-11 at 17 16 16](https://user-images.githubusercontent.com/82387427/121709355-c0b89100-cad8-11eb-8e94-6d87cccaa45a.png)

## Acceptance Criteria

- [x] Adding a new book adds it to this page
- [x] Book Cover and Title are shown

## Complexity
S

## Tasks

- [x] Create feature branch 'library-view'
- [x] Create component for library
- [x] Implement function to map books array in the component
- [x] Implement styleguidist for component
- [x] Add tests
